# Formatters detailed here: http://docs.python.org/2/library/logging.html#logrecord-attributes
version: 1
formatters:
  simple:
    format: 'PID:%(process)d %(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detail:
    format: 'PID:%(process)d %(asctime)s - %(levelname)s - File: %(filename)s - %(funcName)s() - Line: %(lineno)d -  %(message)s'

loggers:
  all:
    handlers: [all]
    propagate: true

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  all:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    when: W0
    backupCount: 4
    filename: logs/pci-server.log

root:
  level: INFO
  handlers: [all, console]
  propagate: true
